### ISSUE TITLE
Add a flag to ignore assets

### ISSUE THREAD

**Issue by Edivad99** [neoforged/snowblower#1]
As the title says, a flag would be useful to avoid versioning the assets. Like nbt...

**Comment by sciwhiz12** [comment]
Snowblower 2.0.14 now provides the `--include` and `--exclude` command-line parameters, which allows selectively including or excluding certain paths from the output.

The two parameters accept glob pattern syntax as specified in [the javadoc for `FileSystem#getPathMatcher`](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/nio/file/FileSystem.html#getPathMatcher(java.lang.String)), and may be repeated for multiple patterns. Inclusive patterns are applied first (where no inclusive patterns means all paths are accepted), and exclusive patterns are applied afterwards.

Note that the paths being matched are relative to _the contents of the JAR file_, not the output directory. (Attempts to match against `src/main/java` or `src/main/resources` will fail.) Glob patterns should not be prefixed with `/` -- they are matched starting from the root already. Unless you have a good reason not to, your patterns should either be prefixed or suffixed with `**`; otherwise, your patterns may not work correctly.

Some examples: _(The quotation marks ensure the shell doesn't parse the glob patterns.)_
- `--include "**.java"` - include only Java source files, and skip everything else. (This would cause the `src/main/resources` folder to be non-existent in the output.)
- `--exclude "**.nbt" --exclude "**.png"` - exclude NBT files (usually, these are structure files) and PNG files
- `--exclude "assets/**"` - exclude the entire `assets` folder
	- `--exclude "assets/"` will _not_ work -- the whole path must match, so the `**` is important.
- `--include "**.java" --exclude "com/mojang/**"` - include only Java source files, but skip files under `com/mojang`.
